general {
    col.active_border = rgba(9178ADff) rgba(161018ff) 45deg
    col.inactive_border = rgba(454148ff) rgba(76507Dff) 45deg
}

group {
    col.border_active = rgba(454148ff) rgba(76507Dff) 45deg
    col.border_inactive = rgba(121013cc) rgba(1A0F15cc) 45deg
    col.border_locked_active = rgba(534759ff) rgba(634C6Aff) 45deg
    col.border_locked_inactive = rgba(151014cc) rgba(171015cc) 45deg
}
