general {
    col.active_border = rgba(D4D1E2ff) rgba(39373Fff) 45deg
    col.inactive_border = rgba(4D4C50ff) rgba(756985ff) 45deg
}

group {
    col.border_active = rgba(4D4C50ff) rgba(756985ff) 45deg
    col.border_inactive = rgba(3B3A3Dcc) rgba(504F5Fcc) 45deg
    col.border_locked_active = rgba(5A5761ff) rgba(676072ff) 45deg
    col.border_locked_inactive = rgba(424148cc) rgba(494954cc) 45deg
}
